docs: add information about Griot
open-sauced/pizza-verse pull request #100
Opened 2024-05-27 20:32 UTC by CBID2

## Description
I noticed that there was no category for Caribbean food, so I created one and added information about Griot . 

## What type of PR is this? (check all applicable)

- [ ] ☝️ Add a pizza fact or trivia
- [ ] 🧑‍🍳 Add a pizza recipe
- [ ] 🗺️ Add a regional pizza
- [x] 🍴 Add a traditional food
- [ ] 📝 Documentation Update

## Related Tickets & Documents
Related to #86 

## Added to documentation?

- [ ] 📜 README.md
- [x] 🙅 no documentation needed

## [optional] What GIF best describes this PR or how it makes you feel?

2024-05-27 21:36 UTC, adiati98 requested changes
Hey @CBID2,

Thank you for this addition! ✨ 

As I'm not too familiar in which continent Caribbean is located, I googled it. Most resources — I link to some of them below for your reference — say that it's part of North America.

- https://en.wikipedia.org/wiki/List_of_sovereign_states_and_dependent_territories_in_North_America
- https://visaguide.world/north-america-caribbean/
- https://www.quora.com/Is-the-Caribbean-a-part-of-North-or-South-America

That said, can you please list your addition under North America?

Thanks. 🙂

2024-05-27 21:40 UTC, CBID2 commented
> Hey @CBID2,
> 
> 
> 
> Thank you for this addition! ✨ 
> 
> 
> 
> As I'm not too familiar in which continent Caribbean is located, I googled it. Most resources — I link to some of them below for your reference — say that it's part of North America.
> 
> 
> 
> - https://en.wikipedia.org/wiki/List_of_sovereign_states_and_dependent_territories_in_North_America
> 
> - https://visaguide.world/north-america-caribbean/
> 
> - https://www.quora.com/Is-the-Caribbean-a-part-of-North-or-South-America
> 
> 
> 
> That said, can you please list your addition under North America?
> 
> 
> 
> Thanks. 🙂 

Made the change @adiati98! 😊

2024-05-28 09:53 UTC, adiati98 requested changes
Hey @CBID2,

I've left a couple of reviews here.

Also, we've merged a PR before yours. So, please resolve the conflicts before we can review your PR. Thanks! ✨

2024-05-28 09:53 UTC, adiati98 commented on world-traditional-food.md
> +  - [Caribbean](#caribbean)
Because we want to list the countries, let's remove the Caribbean here.

2024-05-28 09:53 UTC, adiati98 commented on world-traditional-food.md
> +### Caribbean
Let's remove this as well.

2024-06-02 16:40 UTC, CBID2 commented
Hey @adiati98. I made the changes

2024-06-02 18:14 UTC, adiati98 requested changes
@CBID2 there are things to fix here.

Also, can you update your branch with the `main` branch?
We've merged a PR that added Indian Samosa, but I don't see it here.

Thanks! ✨

2024-06-02 18:14 UTC, adiati98 commented on world-traditional-food.md
> -
I'm not sure why you deleted these. We don't want to remove them. So, please add them back.

2024-06-02 18:14 UTC, adiati98 commented on world-traditional-food.md
>  ## South America
Add a space here.

```suggestion
 <img src="./images/griot.jpg" width="400" alt="a plate of rice and beans with fried plantains and griot topped with pikliz">
 
## South America
```

2024-06-02 21:22 UTC, CBID2 commented
> @CBID2 there are things to fix here.
> 
> Also, can you update your branch with the `main` branch? We've merged a PR that added Indian Samosa, but I don't see it here.
> 
> Thanks! ✨

Hey @adiati98. I made the changes.

2024-06-03 08:40 UTC, adiati98 requested changes
Hey @CBID2,

Can you please ask for review once you've addressed all feedback?
I see you quoted my comment, but you haven't addressed something there.

Thanks.

2024-06-03 11:51 UTC, CBID2 commented
> Hey @CBID2,
> 
> Can you please ask for review once you've addressed all feedback? I see you quoted my comment, but you haven't addressed something there.
> 
> Thanks.

Hey @adiati98. I reread your previous feedback. The information for the Samosa is on line 61. For some odd reason, GitHub won’t let me link it here.

2024-06-03 13:09 UTC, adiati98 commented
@CBID2, have you tried to pull it locally?

2024-06-03 15:42 UTC, CBID2 commented
> @CBID2, have you tried to pull it locally?

Yes @adiati98

2024-06-03 17:33 UTC, adiati98 reviewed
Hey @CBID2,

Thanks for the changes! ✨ 

FYI, I've removed some things as below:

- The foods that you've added to the Table of Contents in [this commit](https://github.com/open-sauced/pizza-verse/pull/100/commits/8023682ab9e9d380d41cedd56a90a4d60bad200d).
-  Duplication of image resource that somehow got added in [this commit](https://github.com/open-sauced/pizza-verse/pull/100/commits/31ee34ed7cff75a585ed62408c57aca3007cd511).

![go time gif](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExb2huMmxkNmYybWlkN3Z6NG9yeTNnanhlcDNzZWp5M2R3cHZpNWcxOCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/fyPFP2It34cgG87ds6/giphy.gif)

2024-06-03 17:33 UTC, adiati98 approved these changes

2024-06-03 17:34 UTC, merged

2024-06-03 17:35 UTC, CBID2 commented
Yay! Now everybody gets to enjoy the awesomeness of Haitian food @adiati98! 😊