fix: pizza-facts missing link to markdown file
open-sauced/pizza-verse pull request #22
Opened 2023-10-01 15:11 UTC by thititongumpun

## Description

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-10-02 14:52 UTC, CBID2 commented
Hi @thititongumpun. There are some sections in your pull request form that are missing information. Can you add them please?

2023-10-02 15:18 UTC, thititongumpun commented
Sure. I add some fun facts.

2023-10-04 02:05 UTC, CBID2 commented
> Sure. I add some fun facts.

To clarify @thititongumpun,  I mean fill out the form in its entirety. I recommend reading [this blog post](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9) to help you. Once you make the changes, tag me again

2023-10-04 13:01 UTC, thititongumpun commented
@CBID2 Sorry for miss understood. I made the changes.

2023-10-04 14:23 UTC, CBID2 commented on pizza-facts-&-trivia.md
> +2. The most popular pizza 🍕 topping is pepperoni, It’s not to hard to figure this one out, but now we have the numbers to prove it! In a HarrisPoll® taken in January of 2016, pepperoni was found to b
[typo] 
```suggestion
2. The most popular pizza 🍕 topping is pepperoni. It’s not to hard to figure this one out, but now we have the numbers to prove it! In a HarrisPoll® taken in January of 2016, pepperoni was found to be the most popular topping followed by Sausage at number two.
```

2023-10-04 14:24 UTC, CBID2 requested changes
Looks great @thititongumpun! :) I just pointed out a typo that needs fixing

2023-10-04 15:34 UTC, thititongumpun commented
@CBID2 Fixed. Thanks.

2023-10-04 15:44 UTC, CBID2 approved these changes
Well done @thititongumpun! :)

2023-10-04 15:44 UTC, merged

2023-10-04 15:47 UTC, CBID2 commented
Yay you just made your first contribution @thititongumpun! :) If you want to do more updates on OpenSauced, join our [Discord](https://discord.com/invite/U2peSNf23P) community! :) We'd love to see more of your ideas! :)