Added a pizza fact
open-sauced/pizza-verse pull request #46
Opened 2023-10-20 21:01 UTC by david-001

## Description

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
#36 

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-10-20 22:49 UTC, CBID2 requested changes
Thanks for your Pull Request @david-001! We've merged in some new PRs since you submitted. Can you merge the latest changes and resolve conflicts? If you need some help with that, check out this post: [Keeping Your Branch Up to Date and Handling Merge Conflicts While Waiting for PR Reviews](https://dev.to/opensauced/keeping-your-branch-up-to-date-and-handling-merge-conflicts-while-waiting-for-pr-reviews-3b3h). Also, can you fill out the description and other sections of your PR's form? It'll make it easier for me and other maintainers to review your contribution. Check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9) to learn how.

2023-10-21 03:13 UTC, david-001 commented
I merged the latest changes and resolved the conflicts. Can you specify which sections of my PR form I need to fill out? The sections I left out are either not relevant or optional. Thanks.

2023-10-21 04:10 UTC, CBID2 commented
> I merged the latest changes and resolved the conflicts. Can you specify which sections of my PR form I need to fill out? The sections I left out are either not relevant or optional. Thanks.

Fill out the `Description` section. In there,briefly describe the fact you add to the file.

2023-10-21 16:03 UTC, david-001 commented
Sorry about that. I filled out the Description.

2023-10-22 00:29 UTC, CBID2 commented on pizza-facts-&-trivia.md
> +11. There is a professional-level sporting competition dedicated to dough-spinning. At the World Pizza Championships, you'll face off against top-tier competitors in five intense events: Freestyle Ac
```suggestion
11. There is a professional-level sporting competition dedicated to dough-spinning. At the World Pizza Championships, you'll face off against top-tier competitors in five intense events: Freestyle Acrobatic Dough Tossing, Largest Dough Stretch, Fastest Dough, Fastest Pizza Box Folding, and the Pizza Triathlon. Additionally, there's an elite Masters division specifically dedicated to Freestyle Acrobatic Dough Tossing.
```

2023-10-22 00:29 UTC, CBID2 requested changes
Hi @david-001. Your entry is off to a great start. Just found a typo that needs fixing.

2023-10-23 19:00 UTC, CBID2 commented on pizza-facts-&-trivia.md
> +   Some say that the queen’s favorite pizza toppings were mozzarella, tomato, and basil. Others say that it was created in honor of Italy’s unification and that the toppings of tomato, basil, and moz
```suggestion
   Some say that the queen’s favorite pizza toppings were mozzarella, tomato, and basil. Others say that it was created in honor of Italy’s unification and that the  toppings represent the red, green, and white on the Italian flag.
```

2023-10-23 19:00 UTC, CBID2 requested changes
You're close @david-001. Just need to make a few more adjustments.

2023-10-24 15:05 UTC, david-001 commented
I think I resolved the conflict this time.

2023-10-24 18:25 UTC, CBID2 approved these changes
Looks good to me

2023-10-24 18:25 UTC, merged