Update rules and steps to contribute in the README
open-sauced/pizza-verse pull request #54
Opened 2023-10-24 18:06 UTC by adiati98

## Description

This PR updates the rules and steps to contribute in the README with details as follow:

- Added a rule for accepting only one added item per contributor.
- Updated the steps to contribute.
- Add links for the git commands.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Relates to #31 

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![there's still one more left GIF](https://media.giphy.com/media/fIQqHKQdwSOsTuWNrf/giphy-downsized.gif)

2023-10-24 18:23 UTC, CBID2 requested changes
Hi @adiati98. You're off to a great start! 😊 I just gave some tips on how to tweak your PR.

2023-10-24 18:23 UTC, CBID2 commented on README.md
> +5. Follow our `style-guide.md` to format your content.
[suggestion] hyperlink the guide so contributors have quicker access to it :) 
```suggestion
5. Follow [our `style-guide.md`](https://github.com/open-sauced/pizza-verse/blob/main/style-guide.md)
to format your content.
```

2023-10-24 18:23 UTC, CBID2 commented on README.md
> +4. You can now add a new pizza fact or trivia to the `pizza-facts-&-trivia.md`, a new regional pizza to the `regional-pizza.md`, or a new recipe to the `pizza-recipes.md` file. Remember, you may only
```suggestion
4. You can now add a new pizza fact or trivia to the [`pizza-facts-&-trivia.md`](https://github.com/open-sauced/pizza-verse/blob/main/pizza-facts-%26-trivia.md),
a new style of pizza to the [`regional-pizza.md`](https://github.com/open-sauced/pizza-verse/blob/main/regional-pizza.md), or a new recipe to the [`pizza-recipes.md`](https://github.com/open-sauced/pizza-verse/blob/main/pizza-recipes.md) file. Remember, you may only submit **one** new item in a file.
```

2023-10-24 18:32 UTC, adiati98 commented
@CBID2 done 😊

2023-10-25 21:01 UTC, CBID2 approved these changes
Looks great @adiati98! 😊 Merge time

2023-10-25 21:02 UTC, merged