Added Some content related to facts about pizza
open-sauced/pizza-verse pull request #55
Opened 2023-10-25 16:20 UTC by kumar007ambi

## Description
I have added some content related to facts about pizza.

## What type of PR is this? (check all applicable)

- [ ☑] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

#36 Add pizza fact or trivia
## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-10-25 16:21 UTC, kumar007ambi commented
@CBID2 please review this PR😀.

2023-10-25 17:12 UTC, CBID2 requested changes
You're off to a good start @kumar007ambi. There are some things that need to be improved. Also, there some commits in there from your PR about Indian pizza in this branch. I highly recommend removing them.

2023-10-25 17:12 UTC, CBID2 commented on pizza-facts-&-trivia.md
> +15. Domino’s Pizza Is the Most Popular Pizza Chain in the world as of 2017. The world’s biggest pizza chain in terms of global sales is Domino’s Pizza. The company has more than 17,000 pizza stores i
```suggestion
15. Domino’s Pizza is the Most Popular Pizza Chain in the world as of 2017. The company has more than 17,000 pizza stores in 90 countries, and this number continues to grow.
```

2023-10-26 10:06 UTC, adiati98 commented
Hi @kumar007ambi,

We've merged a PR before yours. So please [resolve the conflicts](https://github.com/open-sauced/pizza-verse#keeping-branch-up-to-date-and-resolving-merge-conflicts) and fix the suggestion from @CBID2 before we can merge your PR. :)

Also be aware that we're now using unordered list with dash (-) instead of ordered list (number).
Thank you :)

2023-10-26 13:24 UTC, kumar007ambi commented
@CBID2 and @adiati98 I have edited my content according to suggestion.

2023-10-26 13:41 UTC, CBID2 requested changes
You're close @kumar007ambi! :)

2023-10-26 13:41 UTC, CBID2 commented on pizza-facts-&-trivia.md
> +- Domino’s Pizza is the Most Popular Pizza Chain in the world as of 2017. The company has more than 17,000 pizza stores in 90 countries, and this number continues to grow.
```suggestion
- As of 2017, Domino’s Pizza is the most popular pizza chain in the world. The company has more than 17,000 pizza stores in 90 countries, and this number continues to grow.
```

2023-10-26 13:55 UTC, kumar007ambi commented
@CBID2 I have edited my content according to suggestion.

2023-10-26 13:56 UTC, CBID2 approved these changes
Looks great

2023-10-26 13:56 UTC, merged