Feature: New Pizza Trivia Added
open-sauced/pizza-verse pull request #60
Opened 2023-11-04 16:43 UTC by mohdahsanrazakhan

## Description
This PR adds the feature/add-pizza-trivia in **Pizza Trivia** list.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Related to #36

## Mobile & Desktop Screenshots/Recordings
![Pizza Trivia](https://github.com/open-sauced/pizza-verse/assets/57056757/a8c2523d-9067-4642-9b3b-62ae835d1a53)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?
NO

## [optional] What gif best describes this PR or how it makes you feel?
![PeachCatPizzaGIF](https://github.com/open-sauced/pizza-verse/assets/57056757/c857a9f4-1366-4b64-8440-40f760af3321)

2023-11-05 11:38 UTC, adiati98 requested changes
Hi @mohdahsanrazakhan,
Thank you for your PR! 🙌

I left a review here for you to fix before we merge your PR.
Let me know when it's fixed and ready for a review.
Thank you. 🙂

2023-11-05 11:38 UTC, adiati98 commented on pizza-facts-&-trivia.md
> +  - 100
Let's avoid wordy words here.

```suggestion
- How many *acres* worth of pizza do Americans eat daily?
  - 100 acres
```

2023-11-05 18:13 UTC, mohdahsanrazakhan commented
Hi @adiati98 your commit suggestion is committed. Review it.

2023-11-06 10:43 UTC, adiati98 approved these changes
Thank you for the fix, @mohdahsanrazakhan!

For your future reference, it would be helpful for you if you pay more attention to your choice of words and not rush maintainers to review your PR. 🙂

If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P). 😊

![git merge GIF](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

2023-11-06 10:43 UTC, merged