Enhanced description of Nigerian Pizza #32
open-sauced/pizza-verse pull request #76
Opened 2024-05-01 22:24 UTC by madefromjames

## Description

This PR adds the feature of enhancing Nigeria's pizza recipe.

## What type of PR is this? (check all applicable)

- [ ] ☝️ Add a pizza fact or trivia
- [x] 🧑‍🍳 Add a pizza recipe
- [ ] 🗺️ Add a regional pizza
- [ ] 📝 Documentation Update

## Related Tickets & Documents

## Added to documentation?

- [x] 📜 README.md
- [ ] 🙅 no documentation needed

## [optional] What GIF best describes this PR or how it makes you feel?
<img src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Smilies/Partying%20Face.png" alt="Partying Face" width="25" height="25" />

2024-05-02 07:02 UTC, adiati98 requested changes
Hey @madefromjames,

Thank you for your contribution! ✨ 

I have a little review here for you to fix.

Also, please address below things:

- In the "Related Tickets and Documents" section, please link to your issue number, which is #77. And add word "Closes" before the issue number. :)
- Change the PR title to be more descriptive to your changes. For example, "Update the Nigerian Pizza description".

Please let me know if you have any question.

Thank you! 😊

2024-05-02 07:02 UTC, adiati98 commented on pizza-recipes.md
>  ### Nigeria pizza
While we're here, let's capitalize this title.

```suggestion
### Nigeria Pizza
```

2024-05-02 20:09 UTC, madefromjames commented
> Hey @madefromjames,
> 
> Thank you for your contribution! ✨
> 
> I have a little review here for you to fix.
> 
> Also, please address the things below:
> 
> * Change the PR title to be **more descriptive to your changes**. For example, "Feature: Update the Nigerian Pizza description".
> * In the "Related Tickets and Documents" section, please **link to your issue number**, which is [Add a pizza Recipe! (Please Keep This Issue Open) #77](https://github.com/open-sauced/pizza-verse/issues/77). You can see the issue number right beside your issue title, as in the screenshot below. And please add the word "Closes" before the issue number.
>   ![Screenshot 2024-05-02 090457](https://private-user-images.githubusercontent.com/45172775/327342385-86e768c7-7ebf-4869-95a9-c4e118eb0a6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2ODA2MzQsIm5iZiI6MTcxNDY4MDMzNCwicGF0aCI6Ii80NTE3Mjc3NS8zMjczNDIzODUtODZlNzY4YzctN2ViZi00ODY5LTk1YTktYzRlMTE4ZWIwYTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDIwMDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNjNjZWRlNjRiZmJkZGE5ZGY3Mzc5Y2M5YjBmZDAxODBjMzBjM2JlNzRiYTg1MTJjZDJmZTNjODFjMWY3ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dpXy7IFN_qB6xkp9kJeoFgSGJ9-zgFKfy2vFnRk3zFM)
> 
> Please let me know if you have any questions.
> 
> Thank you! 😊

Hi @adiati98 I appreciate your follow-up with me, I have linked the issue number.
<img width="299" alt="image" src="https://github.com/open-sauced/pizza-verse/assets/104380115/01335d13-05c4-400a-a9aa-be37bc59b228">
I have also committed changes to the header `Nigeria Pizza`
Please let me know what more needs to be done.

2024-05-10 07:48 UTC, adiati98 requested changes
Hey @madefromjames,

We don't want to modify any other files than the `pizza-recipes.md` here.

I have a review here for you to fix.

Please let me know when you're done. Thank you. 🙂

2024-05-10 07:48 UTC, adiati98 commented on package-lock.json
Please revert every change that you made in this file.

2024-05-10 17:22 UTC, madefromjames commented on package-lock.json
Okay @adiati98 I'll do that now

2024-05-10 18:08 UTC, madefromjames commented on package-lock.json
> Please revert every change that you made in this file.

I think I have successfully revert the changes. Please let me know if everything is fine now.

2024-05-10 20:45 UTC, adiati98 approved these changes
Thank you, @madefromjames!

![thanks gif](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGVzbDFubml4NXBsMjUzYW54bHhrdGIzcjQxYms3aWQxbDR1aTVpayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/BYoRqTmcgzHcL9TCy1/giphy.gif)

2024-05-13 13:40 UTC, BekahHW approved these changes

2024-05-13 19:17 UTC, merged