feat: Add a pizza fact
open-sauced/pizza-verse pull request #91
Opened 2024-05-13 19:26 UTC by prw760

## Description

This PR adds a pizza fact

## What type of PR is this? (check all applicable)

- [ X] ☝️ Add a pizza fact or trivia
- [ ] 🧑‍🍳 Add a pizza recipe
- [ ] 🗺️ Add a regional pizza
- [ ] 🍴 Add a traditional food
- [ ] 📝 Documentation Update

## Related Tickets & Documents

Relates to #36

## Added to documentation?

- [ ] 📜 README.md
- [ X] 🙅 no documentation needed

## [optional] What GIF best describes this PR or how it makes you feel?

2024-05-14 09:29 UTC, adiati98 requested changes
Hey @prw760,

I left a nitpick review here. 🙂

You can simply click the "commit suggestion" button if you agree with the suggestion whenever you encounter sonething like this in the future.

Also, please mind the bot. I'm making a fix to our GitHub action to include "relate(d/s) to" keywords for linking issues. Your PR template is already good! 👍🏽 

Thanks!

2024-05-14 09:29 UTC, adiati98 commented on pizza-facts-&-trivia.md
> +- "Pizza John’s Jardín Escondido" restaurant in El Castillo, Costa Rica, is widely considered the world’s most remote pizzaria. It is situated in the middle of the rainforest in Volcán Arenal nationa
**Nitpick**: Let's fix the capitalization, spacing, etc., here.

```suggestion
- "Pizza John’s Jardín Escondido" restaurant in El Castillo, Costa Rica, is widely considered the world’s most remote pizzaria. It is situated in the middle of the rainforest in Volcán Arenal National Park — and has fantastic views of mountains, lagoons, and wildlife. The pizzaria is located 80+ miles from the nearest city and approximately 40 miles from the nearest small town. Diners are encouraged to commemorate their visit by signing the pizzeria’s "wall of signatures."
```

2024-05-14 11:32 UTC, adiati98 commented
@prw760 we've merged a PR before yours. So, please [resolve the merge conflicts](https://github.com/open-sauced/pizza-verse?tab=readme-ov-file#resolving-merge-conflicts) before we review your PR.

Thank you! 🙂

2024-05-17 00:31 UTC, prw760 commented
Hi, Ayu.   I accepted your changes, but I cannot click the resolve conflicts area because I don't have write access to the main repo.  Do I have an actionable still -- or am I waiting for the repo managers?   Thanks again for your patience while I'm learning.

2024-05-17 00:55 UTC, closed without merging

2024-05-17 06:22 UTC, adiati98 commented
Hey @prw760,

Answering your question, whenever you see merge conflicts in you PR, you need to resolve them yourself.
Most of the time, maintainers won't do this for you because they don't have the resources to do so.

I've actually gave you the link to resolve conflicts in my previous comment, but I'm dropping it [here](https://github.com/open-sauced/pizza-verse?tab=readme-ov-file#keeping-branch-up-to-date-and-resolving-merge-conflicts) again.

I wrote a [blog post](https://www.freecodecamp.org/news/keep-branches-up-to-date-resolve-merge-conflicts/) as well about resolving merge conflicts if you'd like to learn further. 🙂

2024-05-17 08:00 UTC, adiati98 commented
If you haven't deleted your local branch, I encourage you to try resolving the merge conflicts to practice. 😊